package cn.robertzhang.joke.model.entities.joke;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private Integer avatar_updated_at;
    private Integer last_visited_at;
    private Integer created_at;
    private String state;
    private String last_device;
    private String role;
    private String login;
    private String icon;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Integer avatar_updated_at, Integer last_visited_at, Integer created_at, String state, String last_device, String role, String login, String icon) {
        this.id = id;
        this.avatar_updated_at = avatar_updated_at;
        this.last_visited_at = last_visited_at;
        this.created_at = created_at;
        this.state = state;
        this.last_device = last_device;
        this.role = role;
        this.login = login;
        this.icon = icon;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAvatar_updated_at() {
        return avatar_updated_at;
    }

    public void setAvatar_updated_at(Integer avatar_updated_at) {
        this.avatar_updated_at = avatar_updated_at;
    }

    public Integer getLast_visited_at() {
        return last_visited_at;
    }

    public void setLast_visited_at(Integer last_visited_at) {
        this.last_visited_at = last_visited_at;
    }

    public Integer getCreated_at() {
        return created_at;
    }

    public void setCreated_at(Integer created_at) {
        this.created_at = created_at;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getLast_device() {
        return last_device;
    }

    public void setLast_device(String last_device) {
        this.last_device = last_device;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

}
