package cn.robertzhang.joke.model.entities.joke;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VOTES.
 */
public class Votes {

    private Long id;
    private Integer down;
    private Integer up;

    public Votes() {
    }

    public Votes(Long id) {
        this.id = id;
    }

    public Votes(Long id, Integer down, Integer up) {
        this.id = id;
        this.down = down;
        this.up = up;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDown() {
        return down;
    }

    public void setDown(Integer down) {
        this.down = down;
    }

    public Integer getUp() {
        return up;
    }

    public void setUp(Integer up) {
        this.up = up;
    }

}
